'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentsInfo
    Public Property StdRegNumber As String
    Public Property StdName As String
    Public Property StdDoBirth As Nullable(Of Date)
    Public Property StdRegDate As Nullable(Of Date)
    Public Property StdContact As String
    Public Property StdEmail As String
    Public Property StdDeptCode As Nullable(Of Integer)

End Class
